name: Go Test
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths-ignore:
      - web
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ~/bin/protoc
            ~/.cache
          key: livekit-recorder

      - uses: shogo82148/actions-setup-redis@v1.10.3
        with:
          redis-version: '6.x'
          auto-start: true

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Download Go modules
        run: go mod download

      - name: Go test
        run: go test -tags=test ./...

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ~/bin/protoc
            ~/.cache
          key: livekit-recorder

      - name: Build docker images
        run: docker build -t livekit-recorder-test -f ./build/test/Dockerfile .

      - name: Run tests
        run: docker run --rm livekit-recorder-test
