name: Go Test
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths-ignore:
      - web
      - recorder
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./service
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ~/bin/protoc
            ~/.cache
          key: livekit-recorder-service

      - uses: shogo82148/actions-setup-redis@v1.10.3
        with:
          redis-version: '6.x'
          auto-start: true
      - run: redis-cli ping

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Download Go modules
        run: go mod download

      - name: Download protoc
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
          sudo unzip protoc-3.15.8-linux-x86_64.zip -d /usr
          sudo chmod 755 /usr/bin/protoc

      - name: Install protobuf generators
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go

      - name: Mage Build
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: build
          workdir: ./service

      - name: Mage Test
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: test
          workdir: ./service
